version: '3'
services:
  sample-php-cron:
    build: .
    ports:
      - 3000:80
    volumes:
      - .:/var/www/html
    environment:
      REDIS_URL: redis://redis:6379/
  clock:
    build: .
    volumes:
      - .:/var/www/html
    environment:
      REDIS_URL: redis://redis:6379/
    command: "php cron.php"
  redis:
    image: redis
    ports:
      - 6379:6379
